### PR TITLE
Fix cookie parsing to account for double-quoted values.

### PR DESCRIPTION
**Pull request by robotdan**
Fix cookie parsing to account for double-quoted values.

### CODE REVIEW

**Comment by voidmain** [comment]
What happens if the string is mangled?

`foo="bar`
`foo=bar"`

Do we need to expand the states in the FSM to account for this and handle it gracefully? Or should the value contain the quote in these cases?

**Comment by robotdan** [comment]
> What happens if the string is mangled?
> 
> `foo="bar` `foo=bar"`
> 
> Do we need to expand the states in the FSM to account for this and handle it gracefully? Or should the value contain the quote in these cases?

I thought about that, but these are invalid values from what I can tell. With the current change, I would just strip them and and both of those would end up as `foo=bar`. So we would correct the invalid quoting. 

But we could also ignore this cookie as well and throw it out if it is incorrectly quoted like that.

**Comment by robotdan** [comment]
I added two more tests to assert the missing quote on opening or closing condition to at least assert the current behavior. Open to throwing the cookie out as well.

**Comment by voidmain** [comment]
Works for me!

**Review by voidmain — APPROVED** [review]
LTGM

**Pull request merged**
